# Generated by Django 5.2.12 on 2026-04-23 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20, unique=True, verbose_name='Número de caso')),
                ('sequence_number', models.IntegerField(blank=True, help_text='Número de orden del caso (1, 2, 3, ...)', null=True, unique=True, verbose_name='Número secuencial')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(blank=True, choices=[('PEN', 'Penal'), ('PUB', 'Público'), ('LAB', 'Laboral'), ('CIV', 'Civil'), ('FAM', 'Familia'), ('ADM', 'Administrativo')], max_length=10, null=True, verbose_name='Categoría')),
                ('case_type_specific', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo específico')),
                ('status', models.CharField(choices=[('SIN', 'Sin asignar'), ('ASI', 'Asignado'), ('PRO', 'En proceso'), ('DOC', 'Documentación'), ('CER', 'Cerrado')], default='SIN', max_length=10, verbose_name='Estado')),
                ('current_stage', models.IntegerField(choices=[(0, 'Sin asignar'), (1, 'Asignación de Estudiante'), (2, 'Recopilación de Información'), (3, 'Análisis y Redacción'), (4, 'Revisión con Supervisor'), (5, 'Presentación ante Juzgado')], default=0, verbose_name='Etapa actual del caso')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('closure_type', models.CharField(blank=True, choices=[('FAV', 'A favor del beneficiario'), ('NEG', 'Respuesta negativa al beneficiario'), ('DIS', 'Desistidos')], help_text='Solo se llena cuando el caso se cierra', max_length=10, null=True, verbose_name='Tipo de cierre')),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_cases', to=settings.AUTH_USER_MODEL, verbose_name='Asesor')),
                ('assigned_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante asignado')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_cases', to=settings.AUTH_USER_MODEL, verbose_name='Beneficiario')),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='Secretaría')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('ACT', 'Actualización'), ('ENT', 'Entrevista'), ('OBS', 'Observación'), ('ASI', 'Asignación'), ('DOC', 'Documento'), ('EVE', 'Evento'), ('CAS_MAN', 'Caso Asignado Manualmente'), ('CAS_REV', 'Caso Enviado a Revisión')], default='ACT', max_length=10, verbose_name='Tipo de entrada')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del evento')),
                ('notify', models.BooleanField(default=False, verbose_name='Notificar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_entries', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_entries', to='cases.case', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Entrada de Bitácora',
                'verbose_name_plural': 'Entradas de Bitácora',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('MAN', 'Manual'), ('AUTO', 'Automática')], default='MAN', max_length=4, verbose_name='Tipo de asignación')),
                ('case_category', models.CharField(choices=[('PEN', 'Penal'), ('PUB', 'Público'), ('LAB', 'Laboral'), ('CIV', 'Civil'), ('FAM', 'Familia'), ('ADM', 'Administrativo')], max_length=10, verbose_name='Categoría de caso')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('assigned_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Asesor o asignador')),
                ('assigned_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante asignado')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='cases.case', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Asignación de Caso',
                'verbose_name_plural': 'Asignaciones de Caso',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deadlines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fecha límite',
                'verbose_name_plural': 'Fechas límite',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INA', 'Inactividad'), ('DEA', 'Fecha límite'), ('INF', 'Informativa')], max_length=3)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.case')),
                ('deadline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.casedeadline')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DOC', 'Documento'), ('REC', 'Recibo de Servicios'), ('FOT', 'Foto')], max_length=3, verbose_name='Tipo de Documento')),
                ('file', models.FileField(upload_to='case_documents/%Y/%m/%d/', verbose_name='Archivo')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre original')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Válido')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño del archivo')),
                ('content_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo MIME')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_documents', to='cases.case', verbose_name='Caso')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento de Caso',
                'verbose_name_plural': 'Documentos de Caso',
                'ordering': ['-uploaded_at'],
                'unique_together': {('case', 'document_type')},
            },
        ),
    ]
