# Generated by Django 5.2.12 on 2026-04-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('SIN', 'Sin asignar'), ('DOC', 'Documentación'), ('ASI', 'Asignado'), ('PRO', 'En proceso'), ('ESP', 'Esperando por usuario'), ('REV', 'En revisión'), ('CER', 'Cerrado')], default='SIN', max_length=10, verbose_name='Estado'),
        ),
    ]
